mybatis:
  mapperLocations: classpath*:mappings/*/*.xml
logging:
  path: d:/tmp/
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.S
apollo:
  bootstrap:
    enabled: true
    namespaces: application,fx.config,web.connection


