mybatis:
  mapperLocations: classpath*:mappings/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  path: d:/tmp/
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.S
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
apollo:
  bootstrap:
    enabled: true
    namespaces: application,fx.config,web.connection


