mybatis:
  mapperLocations: classpath*:mappings/*/*.xml
logging:
  path: d:/tmp/
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.S
  redis:
    #数据库索引
    database: 1
    host: potens.top
    port: 7379
    password: potens
    #连接超时时间
    timeout: 10000ms
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 1000ms
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0

